# Generated by Django 2.2 on 2019-04-10 02:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from resident.models import BRPostalCodeField


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.AddField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='resident',
            name='cep',
            field=BRPostalCodeField(blank=True, max_length=9, verbose_name='Cep'),
        ),
        migrations.AddField(
            model_name='resident',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='resident',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='resident',
            name='street',
            field=models.CharField(blank=True, max_length=250, verbose_name='Rua/Av'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.Lot'),
        ),
        migrations.CreateModel(
            name='HouseResident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome do morador')),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de nascimento')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
