# Generated by Django 2.2 on 2019-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_auto_20190414_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='lot',
        ),
        migrations.AddField(
            model_name='resident',
            name='log_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Números do lote'),
        ),
        migrations.AddField(
            model_name='resident',
            name='lot_block',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Block do lote'),
        ),
    ]
