# Generated by Django 2.2 on 2019-04-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_auto_20190417_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='log_number',
        ),
    ]
