# Generated by Django 2.2 on 2019-04-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='block',
            field=models.CharField(default='A', max_length=2, verbose_name='Bloco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.IntegerField(verbose_name='Número do lote'),
        ),
    ]
