# Generated by Django 2.2 on 2019-04-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_auto_20190410_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='block',
            field=models.CharField(max_length=3, verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.IntegerField(max_length=5, verbose_name='Número do lote'),
        ),
    ]
